name: Check project

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update and install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests black flake8 mypy bandit python-dateutil types-requests types-python-dateutil beautifulsoup4

      - name: Check python scripts
        run: |
          black pool-check.py
          flake8 --extend-ignore=E501 pool-check.py
          mypy --strict pool-check.py
          bandit pool-check.py
