name: Run script

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update and install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests python-dateutil beautifulsoup4

      - name: Run python script
        run: |
          python ./pool-check.py
        env:
          LOKI_USER: ${{ secrets.LOKI_USER }}
          LOKI_PASS: ${{ secrets.LOKI_PASS }}
